#!/usr/bin/env python

import sys
import math

def is_prime(number):
    if number < 2:
        return False
    for i in range(2, int(math.sqrt(number)) + 1):
        if number % i == 0:
            return False
    return True

def factorize(number):
    for i in range(2, int(math.sqrt(number)) + 1):
        if number % i == 0 and is_prime(i):
            factor2 = number // i
            if is_prime(factor2):
                return i, factor2
    return None, None

def main(file_path):
    try:
        with open(file_path, 'r') as file:
            for line in file:
                number = int(line)
                factor1, factor2 = factorize(number)
                print(f"{number}={factor1}*{factor2}")
    except FileNotFoundError:
        print(f"Oops! Couldn't find the file '{file_path}'.")
    except ValueError:
        print("Oops! Something went wrong. Check the file for valid numbers.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python rsa.py <file>")
        sys.exit(1)

    file_path = sys.argv[1]
    main(file_path)

